name: setup-serverless-on-gardener

permissions:
  # Required to receive OIDC tokens
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc
  id-token: write

on:
  workflow_dispatch:

jobs:
  # this job simulates control-plane usecase
  # these ateps are needed to be added in the KEB or other tool that provision cluster
  setup-cluster:
    runs-on: ubuntu-latest

    env:
      # gardener service account is used to provision and configure cluister
      GARDENER_SA_CONTENT: ${{ secrets.GARDENER_SA_CONTENT }}
      # path where value of GARDENER_SA_CONTENT will be located
      GARDENER_SA_PATH: /tmp/gardener_sa.yaml
      # path to the kubeconfig used to connect with the cluster
      CLUSTER_KUBECONFIG_PATH: /tmp/cluster_kubeconfig.yaml

    steps:

      - name: save kubeconfig
        # save GARDENER_SA_CONTENT to the right file to use it later as kubeconfig for kubectl 
        run: 'echo "$GARDENER_SA_CONTENT" > $GARDENER_SA_PATH'

      - name: create cluster
        if: false
        # create cluster with the `github-test-oidc: enabled` label to activate OpenIDConnection on it

        # shoot needs following fields with values:
        # spec.kubernetes.enableStaticTokenKubeconfig: true <- we will use it to configure oidc on the cluster
        # spec.extensions[].type: shoot-oidc-service <- enables oidc webhook on the cluster to use a few OpenIDConnect resources at the same time

        # https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/docs/usage/openidconnects.md
        run: |
          kubectl apply --kubeconfig $GARDENER_SA_PATH -f - <<EOF
          kind: Shoot
          apiVersion: core.gardener.cloud/v1beta1
          metadata:
            name: oidc-test
          spec:
            extensions:
            - type: shoot-oidc-service
            provider:
              type: gcp
              infrastructureConfig:
                apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
                kind: InfrastructureConfig
                networks:
                  workers: 10.180.0.0/16
              controlPlaneConfig:
                apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
                kind: ControlPlaneConfig
                zone: europe-west1-d
              workers:
              - name: worker-imbl6
                minimum: 1
                maximum: 2
                maxSurge: 1
                machine:
                  type: c2-standard-8
                  image:
                    name: gardenlinux
                    version: 1312.1.0
                  architecture: amd64
                zones:
                - europe-west1-d
                cri:
                  name: containerd
                volume:
                  type: pd-balanced
                  size: 50Gi
            networking:
              nodes: 10.180.0.0/16
              type: calico
            cloudProfileName: gcp
            region: europe-west1
            secretBindingName: wookiee-project
            kubernetes:
              version: 1.26.11
              enableStaticTokenKubeconfig: true
            purpose: evaluation
            addons:
              kubernetesDashboard:
                enabled: false
              nginxIngress:
                enabled: false
            maintenance:
              timeWindow:
                begin: 010000+0100
                end: 020000+0100
              autoUpdate:
                kubernetesVersion: true
                machineImageVersion: true
            hibernation:
              schedules: []
          EOF
        
      - name: wait for available API
        if: true
        # wait until gardener will create ca secret and setup api
        run: |
          kubectl wait --kubeconfig $GARDENER_SA_PATH --for=condition=SystemComponentsHealthy --timeout=30m shoot/oidc-test

      - name: export cluster kubeconfig
        # export cluster kubeconfig to manage it later
        run: |
          kubectl get secret --kubeconfig $GARDENER_SA_PATH oidc-test.kubeconfig -ojson | jq -r '.data.kubeconfig' | base64 -d > $CLUSTER_KUBECONFIG_PATH

      - name: create OpenIDConnect resource
        if: true
        # create OpenIDConnect resource on the cluster that contains most important informations about OIDC
        # this step should be setup once per gardener namespace

        # here is more info about this resource
        # https://gardener.cloud/docs/extensions/others/gardener-extension-shoot-oidc-service/openidconnects/

        # configuration is based on this article
        # https://community.sap.com/t5/additional-blogs-by-sap/using-github-actions-openid-connect-in-kubernetes/ba-p/13542513
        run: |
          kubectl apply --kubeconfig $CLUSTER_KUBECONFIG_PATH -f - <<EOF
          apiVersion: authentication.gardener.cloud/v1alpha1
          kind: OpenIDConnect
          metadata:
            name: github-oidc-test
          spec:
            clientID: gh-kubernetes-action
            issuerURL: https://token.actions.githubusercontent.com
            usernameClaim: sub
            usernamePrefix: "actions-oidc:"
            requiredClaims:
              repository: pPrecel/gardener-oidc-extension-poc
              workflow: setup-serverless-on-gardener
              ref: refs/heads/main
          EOF
        
      - name: create Role and RoleBinding resources
        if: true
        # create following resources to give access for the open id connection
        run: |
          kubectl apply --kubeconfig $CLUSTER_KUBECONFIG_PATH -f - <<EOF
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: github-oidc-role
          rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "watch", "list"]
            - apiGroups: ["apps"]
              resources: ["deployments"]
              verbs: ["get", "watch", "list", "create", "update", "delete"]
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: github-oidc-binding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: github-oidc-role
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: actions-oidc:repo:pPrecel/gardener-oidc-extension-poc:ref:refs/heads/main
          EOF

      - name: export API ca
        id: api-ca
        # apply-manifest job needs to has access to the API Server
        # because of that this step exports API endpoint and API CA
        run: |
          API_CA=$(kubectl get --kubeconfig $GARDENER_SA_PATH secrets oidc-test.ca-cluster -ojson | jq -r '.data."ca.crt"')
          
          echo data="${API_CA}" >> $GITHUB_OUTPUT
          echo "${#API_CA}"

      - name: export API endpoint
        id: api-endpoint
        run: |
          API_ENDPOINT=$(kubectl get --kubeconfig $GARDENER_SA_PATH shoot oidc-test -ojson | jq -r '.status.advertisedAddresses[] | select(.name=="external") | .url')
          
          echo data="${API_ENDPOINT}" >> $GITHUB_OUTPUT
          echo "${#API_ENDPOINT}"
  
    outputs:
      api-endpoint: ${{ steps.api-endpoint.outputs.data }}
      api-ca: ${{ steps.api-ca.outputs.data }}

  # this job simulates CICD action on the users side
  # these steps should be configured in the GH action that requested gardener cluster creation and use it
  apply-manifest:
    runs-on: ubuntu-latest
    needs: [setup-cluster]

    steps:

      - name: configure OIDC
        id: create-oidc-token
        # this step use envs given by GitHub thanks to `permission.id-token=write` configuration
        # given id-token is exported 
        run: |
          AUDIENCE="gh-kubernetes-action" # clientID
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"

          IDTOKEN=$(curl \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -H "Accept: application/json; api-version=2.0" \
            "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)
          
          echo "::add-mask::${IDTOKEN}"
          echo "id-token=${IDTOKEN}" >> $GITHUB_OUTPUT

      - name: check permissions
        run: |
          echo "$API_CA" | base64 -d > /tmp/ca.crt

          kubectl auth can-i --list \
            --token="${TOKEN}" \
            --server="${API_SERVER}" \
            --certificate-authority="/tmp/ca.crt"
        env:
          TOKEN: "${{ steps.create-oidc-token.outputs.id-token }}"
          API_SERVER: "${{ needs.setup-cluster.outputs.api-endpoint }}"
          API_CA: "${{ needs.setup-cluster.outputs.api-ca }}"